# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Cowardly refusing to access an unloaded tag ingredient:", "A tag ingredient was accessed before tags are loaded - This can break recipes! Report this to the mod in the trace below."]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Cowardly refusing to access an unloaded tag ingredient:", "A tag ingredient was accessed before tags are loaded - This can break recipes! Report this to the mod in the trace below."]
