#.
#URL to send data to.
"Metrics Endpoint URL" = "https://n8n.bysalad.studio/webhook-test/pack-analytics-receiver"
#.
#Identifier for this modpack
"Pack ID" = "shenanigans"
#.
#Interval between keepalive requests, in minutes.
#Range: > -2147483648
"Update Rate" = 10
